Yatru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from app import views
app_name = 'app'
urlpatterns = [
    path('login/',views.loginuser,name='loginuser'),
    path('signup/',views.signupuser,name='signupuser'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('', views.home,name='home'),
    path('myprofile/', views.my_profile_view, name='my-profile-view'),
    path('new-messages/',views.new_messages,name='new_messages'),
    path('view-messages/',views.view_messages,name='view_messages'),
    path('delete-messages/',views.delete_messages,name='delete_messages'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('',views.post_views,name='post_views'),
    path('liked/',views.like_unlike,name='like_unlike'),
    path('add-post/',views.post_add,name='post_add'),
    path('search/',views.search,name='search'),
    

]

app/templates/app/Login.html
{% extends "app/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Login</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            <hr>
            <div class="text-center">
                Need an account? <a href="{% url 'app:signupuser' %}">Sign Up here</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/Signup.html
{% extends "app/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'app:loginuser' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/base.html
{% if user.is_authenticated %}
Logged in as {{user.username}}
<form action="{% url 'app:logoutuser'%}" method='POST'>
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Log Out</button>

</form>

{%else%}


<a href="{% url 'app:loginuser'%}">Log In </a>
<a href="{% url 'app:signupuser' %}">Sign Up </a>

{%endif%}
<a class="navbar-brand" href="{% url 'app:home' %}">Home</a>
<a class="navbar-brand" href="{% url 'app:my-profile-view' %}">Profile</a>
<a class="navbar-brand" href="{% url 'posts:post_views' %}">Posts</a>
<a class="navbar-brand" href="{% url 'app:view_messages' %}">Messages</a>
{%block content%}

{%endblock%}

app/templates/app/create.html
{% extends 'app/base.html'%}
{%block content%}
<form action="" method="POST" class="ui form" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  
    <button type='submit'>
      Update
      
    </button>
    </form>
{%endblock%}

app/templates/app/home.html
{% extends 'app/base.html'%}
{%block content%}

{%endblock%}

app/templates/app/message.html
{% extends 'app/base.html'%}{% comment %} 
{%block content%} 
<h1>Messages</h1>
    <h2 style="background-color:powderblue;">From:{{messages}}</h2>

{% for obj in messages %}
    <p style="background-color:#DCDCDC;">{{obj.content}}</p>
{%endfor%}
{%endblock%} {% endcomment %}


{%block content%}
<form action="{%url 'app:new_messages' %}" class="ui form" enctype='multipart/form-data'>
    <button type='submit'>
      New Message  
    </button>
    </form>
{%if msgs%}
  {% for msg in msgs %}
      <div class="message">
          <div class="message__detail">
              
            <p style="background-color:powderblue;class="message__authort">From:{{msg.author}}</p>
              <p class="message__date">{{msg.date_posted|date:"D/m/y - H:i"}}</p>
          </div>
          <div class="message__content">
              <p class="message__msg">{{msg.content}}</p>
          </div>
      </div>
  {% endfor %}
{%else%}
    <h4 style="text-align:center">You have no Messages :</h4>
{%endif%}
{%endblock%}

app/templates/app/navbar.html
<div class="ui inverted menu">
  <div class="ui container">
    <a href="" class="item">
        <h3>bffbook</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="" class="item">
        Home
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="" class="item">
                        All Profiles
                    </a>
                    <a href="" class="item">
                        Send Invites
                    </a>
                    <a href="" class="item">
                        Received Invites
                    </a>
                </div>
             </div>
        </div>
             <div class="item">
              <form action="" method="GET">
                <div class="ui action left icon input">
                <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                <i class="search icon"></i>
                <button type='submit' class="ui button">Search</button>
                </div>
            </form>
            </div>
        
            <a href="" class="item">
                 {{ request.user }}
            </a>

            <a href="" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>

app/templates/app/profile.html
{% extends 'app/base.html'%}
{% comment %} <form action="" action="POST">
{% csrf_token %}
{{form}}
<button type="submit">Update Profile</button>
</form>
{%if confirm%}
    Updated {{request.user}}
{%endif%} {% endcomment %}

{%block content%}
    <h1> Your Profile </h1>
     <img height= "100px" width ="120px" src="{{profile.avatar.url}}"><br/>
      {{profile.first_name}}<br/>
      {{profile.last_name}}<br/>
      {{profile.bio}}<br/> <hr>
     <form action="" method="POST" class="ui form" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  
    <button type='submit'>
      Update
      
    </button>
    </form>
{%endblock%}
 

app/templates/app/write_message.html
{% extends 'app/base.html'%}
{%block content%}

<form method="POST">{% csrf_token %}
{{form.as_p}}
<button type="submit">Submit</button>
</form>
{%endblock%}