Yatru/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('posts/', include('posts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from app import views
app_name = 'app'
urlpatterns = [
    path('login/',views.loginuser,name='loginuser'),
    path('signup/',views.signupuser,name='signupuser'),
    path('logout/',views.logoutuser,name='logoutuser'),
    path('', views.home,name='home'),
    path('myprofile/', views.my_profile_view, name='my-profile-view'),
    path('new-messages/',views.new_messages,name='new_messages'),
    path('view-messages/',views.view_messages,name='view_messages'),
    path('delete-messages/',views.delete_messages,name='delete_messages'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('',views.post_views,name='post_views'),
    path('liked/',views.like_unlike,name='like_unlike'),
    path('add-post/',views.post_add,name='post_add'),
    path('search/',views.search,name='search'),
    

]

posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator #to validate the type of image
from app.models import Yatru
from datetime import timezone

# Create your models here.
class Post(models.Model):
    no_people = models.IntegerField()
    no_days = models.IntegerField()
    tour_date = models.DateField()
    Gender_types = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    )
    Gender_prefer = models.CharField(max_length=6, choices=Gender_types)
    location = models.CharField(max_length=200, blank=True)
    pic_location = models.ImageField(blank=True, upload_to="posts/")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    detail = models.TextField() 
    liked = models.ManyToManyField(Yatru, blank=True, related_name= 'likes')
    author = models.ForeignKey(Yatru, on_delete=models.CASCADE, related_name = 'posts',blank=True)

    def __str__(self):
        return str(self.location)

    def no_likes(self):
        return self.liked.all().count()
    
    class Meta:
        ordering = ('-created',)

    def save(self, *args, **kwargs):
        self.location = self.location.upper()
        return super(Post, self).save(*args, **kwargs)

LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model): 
    user = models.ForeignKey(Yatru, on_delete=models.CASCADE)
    location_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}-{self.location_post}-{self.value}"
    def total_likes(self):
        return self.likes.count()

posts/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('no_people','no_days','tour_date', 'Gender_prefer','location','detail','author')

posts/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
from .models import Post,Like
from app.models import Yatru
from .forms import PostModelForm
from django.contrib.auth.models import User
import folium,geocoder
# Create your views here.

def post_views(request):
    qs = Post.objects.all()
    context = {
        'qs':qs,
    }

    return render(request,'posts/main.html',context)

def post_add(request):
    
    form = PostModelForm(request.POST,instance=Post())
    if request.method == 'POST':
        newpost=form.save()
        newpost.user=request.user
        newpost.save()
        
    return render(request, 'posts/my_post.html', {'form':PostModelForm()})


def like_unlike(request):
    user = request.user 
    if request.method == 'POST':
        location_post_id = request.POST.get('location_post_id')
        location_obj = Post.objects.get(id=location_post_id)
        profile = Yatru.objects.get(user=user)

        if profile in location_obj.liked.all():
            location_obj.liked.remove(profile)
        else:
            location_obj.liked.add(profile)
        
        like, created = Like.objects.get_or_create(user=profile, location_post_id=location_post_id)

        if not created:
            if like.value=='Like':
                like.value='Unlike'
            else:
                like.value='Like'
            
            location_obj.save()
            like.save()
    return redirect('posts:post_views')
########################################################
# def search(request):  
#     query=request.GET.get('query')
#     query=query.upper()
#     if Post.objects.filter(location=query).exists():
#         allPosts= Post.objects.filter(location=query)
#         params={'allPosts': allPosts}
#         return render(request, 'posts/search.html', params)
#     else:
#         return render(request, 'posts/search.html', {'error':'The keyword you entered not found. You can try the advance search below!'})
########################################################

def search(request): 
    qs = Post.objects.all()
    location_query= request.GET.get('location')
    details_query= request.GET.get('details')
    user_query= request.GET.get('user')
    days_query= request.GET.get('days')
    people_query= request.GET.get('people')
    date_query= request.GET.get('date')
    gender_query= request.GET.get('gender')

    if location_query !='' and location_query is not None:
        qs=qs.filter(location__icontains=location_query)

    elif details_query !='' and details_query is not None:
        qs=qs.filter(detail__icontains=details_query)

    elif user_query !='' and user_query is not None:
        qs=qs.filter(author__icontains=user_query)

    elif days_query !='' and days_query is not None:
        qs=qs.filter(no_days__icontains=days_query)

    elif people_query !='' and people_query is not None:
        qs=qs.filter(no_people__icontains=people_query)

    elif date_query !='' and date_query is not None:
        qs=qs.filter(tour_date__icontains=date_query)

    elif gender_query !='' and gender_query is not None:
        qs=qs.filter(Gender_prefer__icontains=gender_query)
    ##########################################################
    address='Kathmandu'
    location=geocoder.osm(address)
    lat=location.lat 
    lng=location.lng
    country=location.country
    m=folium.Map(height=500,location=[28, 84], zoom_start=7)
    folium.Marker([lat,lng],popup=country).add_to(m)
    m=m._repr_html_()  
    ##########################################################
    context = {
        'qs':qs,
        'm':m,
    }
    return render(request, 'posts/search.html',context)




    

    
  

posts/templates/posts/base.html
{% if user.is_authenticated %}
Logged in as {{user.username}}
<form action="{% url 'app:logoutuser'%}" method='POST'>
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Log Out</button>

</form>

{%else%}


<a href="{% url 'app:loginuser'%}">Log In </a>
<a href="{% url 'app:signupuser' %}">Sign Up </a>

{%endif%}
<a class="navbar-brand" href="{% url 'app:home' %}">Home</a>
<a class="navbar-brand" href="{% url 'app:my-profile-view' %}">Profile</a>
<a class="navbar-brand" href="{% url 'posts:post_views' %}">Posts</a>
<a class="navbar-brand" href="{% url 'app:view_messages' %}">Messages</a>
<a class="navbar-brand" href="{% url 'posts:search' %}">Search</a><br/>

{%block body%}

{%endblock%}

posts/templates/posts/main.html
{% extends 'posts/base.html' %}
{% block body %}

 {% for obj in qs %}
    {{obj.location}}
    {{obj.author}}
<form action ="{%url 'posts:like_unlike' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name='location_post_id' value={{obj.id}}>
    <button type='submit'>Like </button>
</form>
{%endfor%}
<hr/>
<form action="{%url 'posts:post_add' %}" class="ui form" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
    </div>
  </div>
  
    <button type='submit'>
      Add New Post
      
    </button>
    </form>
  
 {%endblock%}

posts/templates/posts/my_post.html
<form method="POST">
    {% csrf_token %}
   {{form.as_p}}
    <button type='submit'>Submit </button>
</form>

posts/templates/posts/search.html
{% comment %} {% extends 'posts/base.html' %} {% endcomment %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Filter Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
{% block body %}<body>
    <main role="main" class="container">
    <a class="navbar-brand" href="{% url 'app:home' %}">Home</a>
      <h3>Filter Your Search</h3><br/>{{ m|safe }}
      <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="location" placeholder="Location" />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>        
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="details" placeholder="Any Specific Details" />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>        
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="user" placeholder="User" />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>        
        </div>
        <div class="form-row">
          <div class="form-group col-md-2 col-lg-2">
            <label for="viewCountMin">No of Days</label>
            <input type="number" min=0 class="form-control" id="viewCountMin" placeholder="0" name="days">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="viewCountMax">No of People</label>
            <input type="number" min=0 class="form-control" id="viewCountMax" placeholder="5" name="people">
          </div>
          <div class="form-group col-md-2 col-lg-2">
            <label for="publishDateMin">Date of Depature</label>
            <input type="date" class="form-control" id="publishDateMin" name="date">
          </div>
          
          <div class="form-group col-md-4">
            <label for="category">Gender</label>
            <select id="category" class="form-control" name="gender">
              <option selected>Male</option>
              <option selected>Female</option>
              <option selected>Other</option>
              {% for cat in categories %}
              <option value="{{ cat }}">{{ cat }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Search</button>
      </form>

      <hr />

      <div class="row">
        <ul>
          {% for query in qs %}
            <li>
              {{ query.location }}
              <span> {{ query.author }}</span>
              <span>
                
                  {{ query.Gender_prefer }}
                
              </span>
              <span>Tour Date: {{ query.tour_date }}</span>
            </li>
            <hr />

          {% endfor %}
        </ul>
      </div>

    </main>
<script type="text/javascript">  
    $('.date').datepicker({  
       format: 'yyyy-mm-dd'  
     });  
</script>  

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
{% endblock %}